import { useState } from 'react'
import './ShareBroadcast.css'

export default function ShareBroadcast({ videoUrl, name, city, language }) {
  const [copied, setCopied] = useState(false)
  const [downloading, setDownloading] = useState(false)

  const shareText = `🎙️ Watch my personalized AI news broadcast for ${city} in ${language}! Generated by NewsGen AI`
  const shareUrl  = videoUrl || window.location.href

  // LinkedIn only works with public URLs — we share the video URL directly as text post
  const linkedInUrl = `https://www.linkedin.com/feed/?shareActive=true&text=${encodeURIComponent(shareText + '\n\n🎬 Video: ' + shareUrl)}`

  // Twitter/X — include video URL in tweet text since direct video share needs API
  const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText + '\n\n🎬 ' + shareUrl)}`

  // WhatsApp — text + URL
  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareText + '\n\n🎬 ' + shareUrl)}`

  // Facebook — sharer with URL (works best with public URLs, fallback to text)
  const facebookUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`

  // Telegram
  const telegramUrl = `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(shareText)}`

  // Email
  const emailUrl = `mailto:?subject=${encodeURIComponent('My AI News Broadcast — NewsGen AI')}&body=${encodeURIComponent(shareText + '\n\nWatch here: ' + shareUrl)}`

  const SHARE_LINKS = [
    { id: 'whatsapp',  label: 'WhatsApp', icon: '💬', color: '#25D366', url: whatsappUrl },
    { id: 'twitter',   label: 'X / Twitter', icon: '🐦', color: '#1DA1F2', url: twitterUrl },
    { id: 'linkedin',  label: 'LinkedIn', icon: '💼', color: '#0A66C2', url: linkedInUrl },
    { id: 'facebook',  label: 'Facebook', icon: '👥', color: '#1877F2', url: facebookUrl },
    { id: 'telegram',  label: 'Telegram', icon: '✈️', color: '#2AABEE', url: telegramUrl },
    { id: 'email',     label: 'Email',    icon: '📧', color: '#888',    url: emailUrl },
  ]

  async function copyLink() {
    try {
      await navigator.clipboard.writeText(shareUrl)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      // Fallback for browsers that block clipboard
      const el = document.createElement('textarea')
      el.value = shareUrl
      document.body.appendChild(el)
      el.select()
      document.execCommand('copy')
      document.body.removeChild(el)
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    }
  }

  async function downloadVideo() {
    if (!videoUrl) return
    setDownloading(true)
    try {
      const res = await fetch(videoUrl)
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `newsgen-broadcast-${name?.toLowerCase().replace(/\s+/g, '-') || 'video'}.mp4`
      a.click()
      URL.revokeObjectURL(url)
    } catch {
      // Fallback: open in new tab
      window.open(videoUrl, '_blank')
    } finally {
      setDownloading(false)
    }
  }

  async function nativeShare() {
    if (!navigator.share) return
    try {
      await navigator.share({
        title: `NewsGen AI — ${name}'s Broadcast`,
        text: shareText,
        url: shareUrl,
      })
    } catch { /* user cancelled */ }
  }

  return (
    <div className="share-bar" aria-label="Share your broadcast">
      <span className="share-bar__label">Share</span>

      <div className="share-bar__btns">
        {SHARE_LINKS.map(s => (
          <a key={s.id} href={s.url} target="_blank" rel="noopener noreferrer"
            className="share-btn" style={{ '--c': s.color }}
            aria-label={`Share on ${s.label}`} title={s.label}>
            <span>{s.icon}</span>
            <span className="share-btn__label">{s.label}</span>
          </a>
        ))}

        <button type="button"
          className={`share-btn share-btn--copy ${copied ? 'share-btn--copied' : ''}`}
          onClick={copyLink} aria-label="Copy video link">
          <span>{copied ? '✓' : '🔗'}</span>
          <span className="share-btn__label">{copied ? 'Copied!' : 'Copy Link'}</span>
        </button>

        {typeof navigator.share === 'function' && (
          <button type="button" className="share-btn share-btn--native"
            onClick={nativeShare} aria-label="Share via device">
            <span>📤</span>
            <span className="share-btn__label">Share</span>
          </button>
        )}
      </div>

      {/* Download tip */}
      <p className="share-bar__tip">
        💡 Tip: Download the video first, then upload directly to LinkedIn/Facebook for best results.
        <button type="button" className="share-bar__dl-btn"
          onClick={downloadVideo} disabled={downloading || !videoUrl}>
          {downloading ? '⏳ Downloading...' : '⬇ Download Video'}
        </button>
      </p>
    </div>
  )
}
